---
extends:
  - './node_modules/@raypatterson/full-metal-webpack/cfg/eslint.config.js'
# settings:
#   import/resolver:
#     webpack:
#       config: './node_modules/@raypatterson/full-metal-webpack/webpack.dev.config.js'
